version: '3'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    # ports:
    #   - 8080:8080
    # depends_on:
    #   - db
    networks: 
      - nginx_network

  nginx:
    image: nginx:1.17
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8080:80
    depends_on:
      - web
    networks:
      - nginx_network

volumes:
  pgdata:

networks: 
  nginx_network:
    driver: bridge